
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-08-14
          override: true
          components: rust-src, rustfmt, clippy
      - uses: jetli/trunk-action@v0.1.0
        with:
          version: 'v0.15.0'
      - name: Build Client
        working-directory: ./client
        run: trunk build --release
      - name: Build Admin Client
        working-directory: ./engine/js
        run: npm install && npm run build
      - name: Build Server
        run: cargo build --release --manifest-path server/Cargo.toml